### ISSUE TITLE
Create an awesome home page

### ISSUE THREAD

**Issue by riolly** [riolly/create-t3-app#7]
I am currently working on this awesome app called [transparency](https://transparency.vercel.app/).
It makes me think to revamp the current boring homepage to also demonstrate the power of this template.
But of course, I don't want to make the boilerplate cluttered with the code.

**Comment by makyfj** [comment]
@riolly that is a pretty cool app/design. I was wondering If you make `t3-extended` a project so we can have both repos for the template and the website.
